/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firstway;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Reaz
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form EmployeePage
     */
    public LoginPage() {
        initComponents();

        this.getContentPane().setBackground(new java.awt.Color(244, 244, 244));

    }

    //Methods
    //domestic status:
    //sysdate:
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FooterPanel = new javax.swing.JPanel();
        Copyright = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        LoginOption = new javax.swing.JPanel();
        adminLoginBtn = new javax.swing.JButton();
        employeeLoginBtn = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        adminLogin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdAdmin = new javax.swing.JTextField();
        txtPassAdmin = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        employeeLogin = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtIdEmp = new javax.swing.JTextField();
        txtPassEmp = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        logLoading = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        Registration = new javax.swing.JPanel();
        AdminRegistration = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtAdminId = new javax.swing.JTextField();
        txtAdminName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAdminAddress = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtAdminContact = new javax.swing.JTextField();
        txtAdminPin = new javax.swing.JPasswordField();
        txtAdminPass = new javax.swing.JPasswordField();
        EmployeeRegistration = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtEmpId = new javax.swing.JTextField();
        txtEmpName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtEmpAddress = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtEmpContact = new javax.swing.JTextField();
        txtEmpPin = new javax.swing.JPasswordField();
        txtEmpPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderPanel.setBackground(new java.awt.Color(102, 102, 102));
        HeaderPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        HeaderPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderPanelMouseDragged(evt);
            }
        });
        HeaderPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderPanelMousePressed(evt);
            }
        });
        HeaderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/closes.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        HeaderPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 30));

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimizes.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        HeaderPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fastway_logo_100x30_gray.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(43, 30));
        HeaderPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        getContentPane().add(HeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        FooterPanel.setBackground(new java.awt.Color(102, 102, 102));
        FooterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        Copyright.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Copyright.setForeground(new java.awt.Color(255, 255, 255));
        Copyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Copyright.setText("Copyright: Raihan Mahamud 2018  |  All Rights Reserved");

        javax.swing.GroupLayout FooterPanelLayout = new javax.swing.GroupLayout(FooterPanel);
        FooterPanel.setLayout(FooterPanelLayout);
        FooterPanelLayout.setHorizontalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterPanelLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(Copyright, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        FooterPanelLayout.setVerticalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Copyright, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
        );

        getContentPane().add(FooterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 600, 20));

        bodyPanel.setBackground(new java.awt.Color(244, 244, 244));
        bodyPanel.setLayout(new java.awt.CardLayout());

        LoginOption.setBackground(new java.awt.Color(244, 244, 244));
        LoginOption.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        adminLoginBtn.setBackground(new java.awt.Color(120, 60, 60));
        adminLoginBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminLoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        adminLoginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin_login.png"))); // NOI18N
        adminLoginBtn.setMaximumSize(new java.awt.Dimension(171, 121));
        adminLoginBtn.setMinimumSize(new java.awt.Dimension(171, 121));
        adminLoginBtn.setPreferredSize(new java.awt.Dimension(171, 121));
        adminLoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminLoginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminLoginBtnMouseExited(evt);
            }
        });
        adminLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginBtnActionPerformed(evt);
            }
        });

        employeeLoginBtn.setBackground(new java.awt.Color(120, 60, 60));
        employeeLoginBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        employeeLoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeeLoginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/employ_login.png"))); // NOI18N
        employeeLoginBtn.setMaximumSize(new java.awt.Dimension(171, 121));
        employeeLoginBtn.setMinimumSize(new java.awt.Dimension(171, 121));
        employeeLoginBtn.setPreferredSize(new java.awt.Dimension(171, 121));
        employeeLoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeeLoginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeeLoginBtnMouseExited(evt);
            }
        });
        employeeLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeLoginBtnActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(120, 60, 60));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Close");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginOptionLayout = new javax.swing.GroupLayout(LoginOption);
        LoginOption.setLayout(LoginOptionLayout);
        LoginOptionLayout.setHorizontalGroup(
            LoginOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginOptionLayout.createSequentialGroup()
                .addGroup(LoginOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginOptionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton11))
                    .addGroup(LoginOptionLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(adminLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(employeeLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        LoginOptionLayout.setVerticalGroup(
            LoginOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginOptionLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addGroup(LoginOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142)
                .addComponent(jButton11)
                .addContainerGap())
        );

        bodyPanel.add(LoginOption, "card3");

        adminLogin.setBackground(new java.awt.Color(244, 244, 244));
        adminLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        adminLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Admin Login", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(48, 24, 24))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(48, 24, 24));
        jLabel7.setText("User Id:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(48, 24, 24));
        jLabel8.setText("Password:");

        txtIdAdmin.setBackground(new java.awt.Color(244, 244, 244));
        txtIdAdmin.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtIdAdmin.setForeground(new java.awt.Color(51, 51, 51));

        txtPassAdmin.setBackground(new java.awt.Color(244, 244, 244));
        txtPassAdmin.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtPassAdmin.setForeground(new java.awt.Color(51, 51, 51));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Forget Password");

        jCheckBox1.setBackground(new java.awt.Color(244, 244, 244));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBox1.setText(" Remember Password");

        jButton3.setBackground(new java.awt.Color(255, 153, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Registration With Pin");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jCheckBox1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8))
                                    .addGap(41, 41, 41)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtIdAdmin)
                                        .addComponent(txtPassAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIdAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPassAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jCheckBox1))
                .addGap(31, 31, 31)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        adminLogin.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 440, 300));

        jButton5.setBackground(new java.awt.Color(120, 60, 60));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        adminLogin.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        bodyPanel.add(adminLogin, "card4");

        employeeLogin.setBackground(new java.awt.Color(244, 244, 244));
        employeeLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        employeeLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(244, 244, 244));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Employee Login", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(48, 24, 24))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(48, 24, 24));
        jLabel11.setText("User Id:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(48, 24, 24));
        jLabel12.setText("Password:");

        txtIdEmp.setBackground(new java.awt.Color(244, 244, 244));
        txtIdEmp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtIdEmp.setForeground(new java.awt.Color(51, 51, 51));

        txtPassEmp.setBackground(new java.awt.Color(244, 244, 244));
        txtPassEmp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtPassEmp.setForeground(new java.awt.Color(51, 51, 51));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Forget Password");

        jCheckBox2.setBackground(new java.awt.Color(244, 244, 244));
        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBox2.setText(" Remember Password");

        jButton4.setBackground(new java.awt.Color(255, 153, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("Login");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Registration With Pin");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCheckBox2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdEmp)
                                    .addComponent(txtPassEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(logLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtIdEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPassEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jCheckBox2))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        employeeLogin.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 440, 300));

        jButton6.setBackground(new java.awt.Color(120, 60, 60));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        employeeLogin.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        bodyPanel.add(employeeLogin, "card5");

        Registration.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Registration.setLayout(new java.awt.CardLayout());

        AdminRegistration.setBackground(new java.awt.Color(244, 244, 244));
        AdminRegistration.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setBackground(new java.awt.Color(120, 60, 60));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        AdminRegistration.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        jPanel3.setBackground(new java.awt.Color(244, 244, 244));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Admin Registration", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(48, 24, 24))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setBackground(new java.awt.Color(255, 153, 0));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Register");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 90, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("User Id");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 70, 30));

        txtAdminId.setBackground(new java.awt.Color(244, 244, 244));
        txtAdminId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtAdminId.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(txtAdminId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 210, 30));

        txtAdminName.setBackground(new java.awt.Color(244, 244, 244));
        txtAdminName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtAdminName.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(txtAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 210, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 70, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Address");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 70, 30));

        txtAdminAddress.setBackground(new java.awt.Color(244, 244, 244));
        txtAdminAddress.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtAdminAddress.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(txtAdminAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 210, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Password");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 70, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Pin Number");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 70, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Contact");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 70, 30));

        txtAdminContact.setBackground(new java.awt.Color(244, 244, 244));
        txtAdminContact.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtAdminContact.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(txtAdminContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 210, 30));

        txtAdminPin.setBackground(new java.awt.Color(244, 244, 244));
        txtAdminPin.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtAdminPin.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(txtAdminPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 210, 30));

        txtAdminPass.setBackground(new java.awt.Color(244, 244, 244));
        txtAdminPass.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtAdminPass.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(txtAdminPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 210, 30));

        AdminRegistration.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 440, 380));

        Registration.add(AdminRegistration, "card2");

        EmployeeRegistration.setBackground(new java.awt.Color(244, 244, 244));
        EmployeeRegistration.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setBackground(new java.awt.Color(120, 60, 60));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        EmployeeRegistration.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        jPanel4.setBackground(new java.awt.Color(244, 244, 244));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true), "Employee Registration", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(48, 24, 24))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setBackground(new java.awt.Color(255, 153, 0));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Register");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 90, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("User Id");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 70, 30));

        txtEmpId.setBackground(new java.awt.Color(244, 244, 244));
        txtEmpId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtEmpId.setForeground(new java.awt.Color(51, 51, 51));
        jPanel4.add(txtEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 210, 30));

        txtEmpName.setBackground(new java.awt.Color(244, 244, 244));
        txtEmpName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtEmpName.setForeground(new java.awt.Color(51, 51, 51));
        jPanel4.add(txtEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 210, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Name");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 70, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Address");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 70, 30));

        txtEmpAddress.setBackground(new java.awt.Color(244, 244, 244));
        txtEmpAddress.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtEmpAddress.setForeground(new java.awt.Color(51, 51, 51));
        jPanel4.add(txtEmpAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 210, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Password");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 70, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Pin Number");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 70, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Contact");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 70, 30));

        txtEmpContact.setBackground(new java.awt.Color(244, 244, 244));
        txtEmpContact.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtEmpContact.setForeground(new java.awt.Color(51, 51, 51));
        jPanel4.add(txtEmpContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 210, 30));

        txtEmpPin.setBackground(new java.awt.Color(244, 244, 244));
        txtEmpPin.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtEmpPin.setForeground(new java.awt.Color(51, 51, 51));
        jPanel4.add(txtEmpPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 210, 30));

        txtEmpPassword.setBackground(new java.awt.Color(244, 244, 244));
        txtEmpPassword.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtEmpPassword.setForeground(new java.awt.Color(51, 51, 51));
        jPanel4.add(txtEmpPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 210, 30));

        EmployeeRegistration.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 440, 380));

        Registration.add(EmployeeRegistration, "card2");

        bodyPanel.add(Registration, "card6");

        getContentPane().add(bodyPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int mousepX;
    int mousepY;
    private void HeaderPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderPanelMouseDragged
        // TODO add your handling code here:
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        this.setLocation(kordinatX - mousepX, kordinatY - mousepY);
    }//GEN-LAST:event_HeaderPanelMouseDragged

    private void HeaderPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderPanelMousePressed
        // TODO add your handling code here:
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_HeaderPanelMousePressed

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setOpaque(true);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setBackground(Color.red);
        jLabel1.setOpaque(true);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        LoginPage.this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jLabel2.setBackground(new java.awt.Color(144, 147, 255));
        jLabel2.setOpaque(true);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setOpaque(true);
    }//GEN-LAST:event_jLabel2MouseExited

    private void adminLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginBtnActionPerformed
        // TODO add your handling code here:
        LoginOption.setVisible(false);
        adminLogin.setVisible(true);
        employeeLogin.setVisible(false);
        Registration.setVisible(false);
        AdminRegistration.setVisible(false);
        EmployeeRegistration.setVisible(false);
    }//GEN-LAST:event_adminLoginBtnActionPerformed

    private void employeeLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeLoginBtnActionPerformed
        // TODO add your handling code here:
        logLoading.setVisible(false);

        LoginOption.setVisible(false);
        adminLogin.setVisible(false);
        employeeLogin.setVisible(true);
        Registration.setVisible(false);
        AdminRegistration.setVisible(false);
        EmployeeRegistration.setVisible(false);
    }//GEN-LAST:event_employeeLoginBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        LoginOption.setVisible(true);
        adminLogin.setVisible(false);
        employeeLogin.setVisible(false);
        Registration.setVisible(false);
        AdminRegistration.setVisible(false);
        EmployeeRegistration.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            empId = txtIdEmp.getText();
            empPass = txtPassEmp.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/fastway", "root", "root");
//            if(c!=null){JOptionPane.showMessageDialog(null, "connected");}
            String getData = "SELECT name, user_id, password FROM fastway.employee WHERE user_id=? AND password=?";
            PreparedStatement pst = c.prepareStatement(getData);
            pst.setString(1, empId);
            pst.setString(2, empPass);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                empName = rs.getString(1);
                logLoading.setVisible(true);
                EmployeePage em = new EmployeePage(empName);
                em.setVisible(true);
                LoginPage.this.dispose();
            } else {
                logLoading.setVisible(false);
                JOptionPane.showMessageDialog(null, "Id or Password Is Incorrect");
            }

        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch (SQLException ex) {
            ex.printStackTrace();

        }
    }//GEN-LAST:event_jButton4ActionPerformed
    //Global Variables for login
    public String adminId;
    public String adminPass;

    public String empId;
    public String empPass;

    //Global Variables for Name of Admin and Employee;
    public String adminName;
    public String empName;


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            adminId = txtIdAdmin.getText();
            adminPass = txtPassAdmin.getText();
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/fastway", "root", "root");
//            if(c!=null){JOptionPane.showMessageDialog(null, "connected");}
            String getData = "SELECT name, user_id, password FROM fastway.admin WHERE user_id=? AND password=?";
            PreparedStatement pst = c.prepareStatement(getData);
            pst.setString(1, adminId);
            pst.setString(2, adminPass);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                adminName = rs.getString(1);
                AdminPage adm = new AdminPage(adminName);
                adm.setVisible(true);
//                    setAdminName(rs.getString(1));
                LoginPage.this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Id or Password Is Incorrect");
            }

        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        LoginOption.setVisible(true);
        adminLogin.setVisible(false);
        employeeLogin.setVisible(false);
        Registration.setVisible(false);
        AdminRegistration.setVisible(false);
        EmployeeRegistration.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        LoginOption.setVisible(false);
        adminLogin.setVisible(true);
        employeeLogin.setVisible(false);
        Registration.setVisible(false);
        AdminRegistration.setVisible(false);
        EmployeeRegistration.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:       
        String adminpin = "ADMIN10";
        String uid = txtAdminId.getText();
        String nam = txtAdminName.getText();
        String pass = txtAdminPin.getText();
        String addr = txtAdminAddress.getText();
        String cont = txtAdminContact.getText();
        String getpin = txtAdminPin.getText();

        if (adminpin.matches(getpin)) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/fastway", "root", "root");
//              if(c!=null){JOptionPane.showMessageDialog(null, "connected");}
                String adminData = "INSERT INTO fastway.admin (user_id, password, name, address, contact, rank) VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement pst = c.prepareStatement(adminData);
                pst.setString(1, uid);
                pst.setString(2, pass);
                pst.setString(3, nam);
                pst.setString(4, addr);
                pst.setString(5, cont);
                pst.setString(6, "Admin");

                int i = pst.executeUpdate();
                if (i > 0) {
                    JOptionPane.showMessageDialog(null, "Registration Successful");
                    JOptionPane.showMessageDialog(null, "Login to Access");
                    LoginOption.setVisible(false);
                    adminLogin.setVisible(true);
                    employeeLogin.setVisible(false);
                    Registration.setVisible(false);
                    AdminRegistration.setVisible(false);
                    EmployeeRegistration.setVisible(false);
                }

            } catch (ClassNotFoundException ex) {
                ex.printStackTrace();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pin is incorrect!");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        LoginOption.setVisible(false);
        adminLogin.setVisible(false);
        employeeLogin.setVisible(true);
        Registration.setVisible(false);
        AdminRegistration.setVisible(false);
        EmployeeRegistration.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String emppin = "EMPLOYEE100";
        String uid = txtEmpId.getText();
        String nam = txtEmpName.getText();
        String pass = txtEmpPin.getText();
        String addr = txtEmpAddress.getText();
        String cont = txtEmpContact.getText();
        String getpin = txtEmpPin.getText();

        if (emppin.matches(getpin)) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/fastway", "root", "root");
//              if(c!=null){JOptionPane.showMessageDialog(null, "connected");}
                String adminData = "INSERT INTO fastway.employee (user_id, password, name, address, contact, rank) VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement pst = c.prepareStatement(adminData);
                pst.setString(1, uid);
                pst.setString(2, pass);
                pst.setString(3, nam);
                pst.setString(4, addr);
                pst.setString(5, cont);
                pst.setString(6, "Employee");

                int i = pst.executeUpdate();
                if (i > 0) {
                    JOptionPane.showMessageDialog(null, "Registration Successful");
                    JOptionPane.showMessageDialog(null, "Login to Access");
                    LoginOption.setVisible(false);
                    adminLogin.setVisible(false);
                    employeeLogin.setVisible(true);
                    Registration.setVisible(false);
                    AdminRegistration.setVisible(false);
                    EmployeeRegistration.setVisible(false);
                }

            } catch (ClassNotFoundException ex) {
                ex.printStackTrace();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pin is incorrect!");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        LoginOption.setVisible(false);
        adminLogin.setVisible(false);
        employeeLogin.setVisible(false);
        Registration.setVisible(true);
        AdminRegistration.setVisible(true);
        EmployeeRegistration.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        LoginOption.setVisible(false);
        adminLogin.setVisible(false);
        employeeLogin.setVisible(false);
        Registration.setVisible(true);
        AdminRegistration.setVisible(false);
        EmployeeRegistration.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        LoginPage.this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void adminLoginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLoginBtnMouseEntered
        // TODO add your handling code here:
        adminLoginBtn.setBackground(new java.awt.Color(180, 90, 90));
        employeeLoginBtn.setBackground(new java.awt.Color(120, 60, 60));
    }//GEN-LAST:event_adminLoginBtnMouseEntered

    private void adminLoginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLoginBtnMouseExited
        // TODO add your handling code here:
        adminLoginBtn.setBackground(new java.awt.Color(120, 60, 60));
        employeeLoginBtn.setBackground(new java.awt.Color(120, 60, 60));
    }//GEN-LAST:event_adminLoginBtnMouseExited

    private void employeeLoginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeLoginBtnMouseEntered
        // TODO add your handling code here:
        adminLoginBtn.setBackground(new java.awt.Color(120, 60, 60));
        employeeLoginBtn.setBackground(new java.awt.Color(180, 90, 90));
    }//GEN-LAST:event_employeeLoginBtnMouseEntered

    private void employeeLoginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeLoginBtnMouseExited
        // TODO add your handling code here:
        adminLoginBtn.setBackground(new java.awt.Color(120, 60, 60));
        employeeLoginBtn.setBackground(new java.awt.Color(120, 60, 60));
    }//GEN-LAST:event_employeeLoginBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminRegistration;
    private javax.swing.JLabel Copyright;
    private javax.swing.JPanel EmployeeRegistration;
    private javax.swing.JPanel FooterPanel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel LoginOption;
    private javax.swing.JPanel Registration;
    private javax.swing.JPanel adminLogin;
    private javax.swing.JButton adminLoginBtn;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel employeeLogin;
    private javax.swing.JButton employeeLoginBtn;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logLoading;
    private javax.swing.JTextField txtAdminAddress;
    private javax.swing.JTextField txtAdminContact;
    private javax.swing.JTextField txtAdminId;
    private javax.swing.JTextField txtAdminName;
    private javax.swing.JPasswordField txtAdminPass;
    private javax.swing.JPasswordField txtAdminPin;
    private javax.swing.JTextField txtEmpAddress;
    private javax.swing.JTextField txtEmpContact;
    private javax.swing.JTextField txtEmpId;
    private javax.swing.JTextField txtEmpName;
    private javax.swing.JPasswordField txtEmpPassword;
    private javax.swing.JPasswordField txtEmpPin;
    private javax.swing.JTextField txtIdAdmin;
    private javax.swing.JTextField txtIdEmp;
    private javax.swing.JPasswordField txtPassAdmin;
    private javax.swing.JPasswordField txtPassEmp;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the adminName
     */
//    public String getAdminName() {
//        return adminName;
//    }
    /**
     * @param adminName the adminName to set
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    /**
     * @return the empName
     */
//    public String getEmpName() {
//        return empName;
//    }
    /**
     * @param empName the empName to set
     */
    public void setEmpName(String empName) {
        this.empName = empName;
    }
}
